version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    #bundle exec unicorn_rails -c config/unicorn.rb -E development -D
    ports:
      - "10801:10801"
    volumes:
      - .:/app
    tty: true
    stdin_open: true
