version: '3'
services:
  dind:
    build:
      context: .
      dockerfile: ./ecr/Dockerfile
    volumes:
        - ..:/app
    working_dir: /app
    #command: bundle install --path vendor/bundle
    command: hostname